server:
  port: 8081

spring:
  datasource:
    # PostgreSQL Configuration
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver

  jpa:
    # database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop  # TEMPORARY: Will recreate database on restart
    show-sql: true
    properties:
      hibernate:
        format_sql: true


smartshop:
  tva-rate: 0.20
